config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
            skip: [:sessions, :passwords, :registrations]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    get "setting/profile", to: "users/registrations#edit"
    patch "setting/profile", to: "users/registrations#update"
    delete "delete", to: "users/registrations#destroy"
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    delete "logout", to: "users/sessions#destroy"
    get "forgot_password", to: "users/passwords#new"
    post "forgot_password", to: "users/passwords#create"
    get "password_reset", to: "users/passwords#edit"
    put "password_reset", to: "users/passwords#update"
  end

  get "search", to: "pages#search"

  get "setting/password", to: "users#edit"
  patch "setting/password", to: "users#update_password"
  get "about", to: "pages#about"

  resources :users, only: :show do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: [:index]

  # resources :rooms, only: [:index, :show, :create, :update, :destroy]

  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :title, :content, :pictures, :chart
    end
  end

  resources :pictures, only: [:create, :destroy]

  resources :comments, only: [:create, :edit, :update, :destroy] do
    member do
      get :cancel
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "pages#home"

  mount ActionCable.server => "/cable"
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user

  after_destroy_commit :delete_notifications
  
  has_many :comments, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  accepts_nested_attributes_for :pictures

  validates :title, presence: true
  validates :content, presence: true
  validates :label1, presence: true, length: { maximum: 10 }
  validates :label2, presence: true, length: { maximum: 10 }
  validates :label3, presence: true, length: { maximum: 10 }
  validates :label4, length: { maximum: 10 }
  validates :label5, length: { maximum: 10 }
  validates :data1, presence: true
  validates :data2, presence: true
  validates :data3, presence: true

  scope :with_user, -> { includes(:user) }

  scope :with_pictures, -> { includes(:pictures) }

  scope :order_by_created, -> { order(created_at: :desc) }

  scope :order_by_views_count, -> { order(view_count: :desc) }

  scope :order_by_likes_count, -> {
    joins(:user)
    .joins(:likes)
    .select("articles.id, articles.title, articles.created_at, articles.user_id, users.name, users.avatar, count(likes.article_id) as likes_count")
    .group("likes.article_id")
    .order("likes_count DESC")
    .order("articles.created_at DESC")
  }

  def cover_picture
    if self.pictures.size > 0
      if self.pictures[0].image.present?
        self.pictures[0].image.to_s
      else
        "blank.jpg"
      end
    else
      "blank.jpg"
    end
  end

  def set_labels
    self.attributes.map { |key, value| value if key.include?("label") }.reject { |value| value.blank? }
  end

  def set_data
    self.attributes.map { |key, value| value if key.include?("data") }.reject { |value| value.blank? }
  end

  private

    def delete_notifications
      Notification.where(article_id: self.id).destroy_all
    end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: [:show]
    before_action :correct_user, only: [:title, :content, :pictures, :chart, :update, :destroy]

    def new
        @article = current_user.articles.build
        3.times { @article.pictures.build }
    end

    def create
        @article = current_user.articles.build(article_params)
        if @article.save
            redirect_to @article, notice: "Success!!"
        else
            create_form(@article.pictures)
            render "new"
        end
    end

    def show
        @article = Article.find(params[:id])
        @article.increment(:view_count, 1) if user_signed_in? && current_user.id != @article.user_id
        @pictures = @article.pictures.reject { |picture| picture.image.blank? }
        gon.labels = @article.set_labels
        gon.data = @article.set_data
    end

    def title
        @article = Article.find(params[:id])
    end

    def content
        @article = Article.find(params[:id])
    end

    def pictures
        @article = Article.find(params[:id])
        @picture = @article.pictures.build
        @pictures = @article.pictures.reject { |picture| picture.image.blank? }
    end

    def chart
        @article = Article.find(params[:id])
        gon.labels = @article.set_labels
        gon.data = @article.set_data
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(update_article_params)
            flash[:notice] = "更新しました。"
        else
            flash[:alert] = "入力に誤りがあります。"
        end
        redirect_back(fallback_location: request.referrer)
    end

    def destroy
        Article.find(params[:id]).destroy
        redirect_to current_user, notice: "Deleted!!"
    end

    private

    def article_params
        params.require(:article).permit(
            :title,
            :content,
            :label1, :label2, :label3, :label4, :label5,
            :data1, :data2, :data3, :data4, :data5,
            pictures_attributes: [:image]
        )
    end

    def update_article_params
        params.require(:article).permit(:title,
            :content,
            :label1, :label2, :label3, :label4, :label5,
            :data1, :data2, :data3, :data4, :data5,
            pictures_attributes: [:image, :_destory, :id])
    end

    def correct_user
        @article = current_user.articles.find_by(id: params[:id])
        redirect_to root_url if @article.blank?
    end

    def create_form(pictures)
        case pictures.size
        when 0
            3.times { pictures.build }
        when 1
            2.times { pictures.build }
        when 2
            pictures.build
        end
    end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
    def correct_user?
        current_user.articles.find_by(id: params[:id])
    end
end

app/views/articles/_articles.html.erb
<% object.each do |article| %>
    <div class="tr-Item">
        <%= link_to article.user, class: 'tr-Item_userImage' do %>
            <%= image_tag article.user.avatar_url %>
        <% end %>
        <div class="tr-Item_body">
            <%= link_to article.title, article, class: 'tr-Item_title' %>
            <div class="tr-Item_meta">
                <span>by <%= link_to article.user.name, article.user, class: 'tr-Item_author' %> </span>
                <time> <%= article.created_at.strftime('%Y年%m月%d日') %> </time>
            </div>
        </div>
        <div class="tr-Item_status">
            <div class="tr-Item_likes">
                <span class="fas fa-thumbs-up"></span>
                <span class="likes-count"> <%= Like.where(article_id: article.id).count %> </span>
            </div>
            <div class="tr_Item_comments">
                <span class="far fa-comment"></span>
                <span class="comments-count"> <%= Comment.where(article_id: article.id).count %> </span>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_edit.html.erb
<ul>
  <li class="edit-header <%= current_page?(title_article_path) ? "current-page" : "different-page" %>"><%= link_to 'タイトル', title_article_path(@article), class: 'edit-path' %></li>
  <li class="edit-header <%= current_page?(content_article_path) ? "current-page" : "different-page" %>"><%= link_to '投稿内容', content_article_path(@article), class: 'edit-path' %></li>
  <li class="edit-header <%= current_page?(pictures_article_path) ? "current-page" : "different-page" %>"><%= link_to '写真', pictures_article_path(@article), class: 'edit-path' %></li>
  <li class="edit-header <%= current_page?(chart_article_path) ? "current-page" : "different-page" %>"><%= link_to 'グラフ', chart_article_path(@article), class: 'edit-path' %></li>
</ul>

app/views/articles/_list.html.erb
<% @articles.each do |article| %>
  <div class="articleItemWrapper" id="posted-order">
    <div class="articleItem_image">
      <%= link_to article do %>
        <%= image_tag article.cover_picture, size: '340x220' %>
      <% end %>
    </div>
    <div class="articleItemBody">
      <%= link_to article.title, article, class: 'articleItem_title' %>
      <div class="articleItem_content">
        <div class="articleItem_content_main">
          <% if article.content.length > 20 %>
            <%= article.content[0, 20] + "....." %>
          <% else %>
            <%= article.content %>
          <% end %>
        </div>
        <div class="articleItem_read">
          <%= link_to '続きを読む', article, class: 'rede-more' %>
        </div>
      </div>
      <hr>
      <div class="articleItem_meta">
        <div class="article_userInfo">
          <span>
            by
            <%= link_to article.user.name, article.user, class: 'tr-Item_author' %>
          </span>
        </div>
        <div class="article_statusInfo">
          <div class="article_likes">
            <span class="fas fa-thumbs-up"></span>
            <span> <%= article.likes.count %> </span>
          </div>
          <div class="article_comments">
            <span class="far fa-comment"></span>
            <span> <%= article.comments.count %> </span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/chart.html.erb
<div class="article-edit-body">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render 'edit' %>
      </div>
      <div class="col-md-8">
        <h2 class="edit-title">グラフを編集する </h2>
        <div class="edit-chart">
          <canvas id="myRadarChart"></canvas>
        </div>
        <div class="editChart_form">
          <%= form_for @article do |f| %>
            <div class="editorChart_box">
              <div class="editorChart_label form-layout">
                <h6><span class="badge badge-danger">必須</span></h6>
                <%= f.text_field :label1, placeholder: 'ラベル１', class: 'form-control mr-3' %>
              </div>
              <div class="editorChart_data form-layout">
                <h6><span class="badge badge-danger">必須</span></h6>
                <%= f.select :data1, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
              </div>
            </div>
            <div class="editorChart_box">
              <div class="editorChart_label form-layout">
                <h6><span class="badge badge-danger">必須</span></h6>
                <%= f.text_field :label2, placeholder: 'ラベル2', class: 'form-control mr-3' %>
              </div>
              <div class="editorChart_data form-layout">
                <h6><span class="badge badge-danger">必須</span></h6>
                <%= f.select :data2, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
              </div>
            </div>
            <div class="editorChart_box">
              <div class="editorChart_label form-layout">
                <h6><span class="badge badge-danger">必須</span></h6>
                <%= f.text_field :label3, placeholder: 'ラベル3', class: 'form-control mr-3' %>
              </div>
              <div class="editorChart_data form-layout">
                <h6><span class="badge badge-danger">必須</span></h6>
                <%= f.select :data3, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
              </div>
            </div>
            <div class="editorChart_box">
              <div class="editorChart_label form-layout">
              <%= f.text_field :label4, placeholder: 'ラベル4', class: 'form-control mr-3' %>
            </div>
              <div class="editorChart_data form-layout">
                <%= f.select :data4, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
              </div>
            </div>
            <div class="editorChart_box">
              <div class="editorChart_label form-layout">
                <%= f.text_field :label5, placeholder: 'ラベル5', class: 'form-control mr-3' %>
              </div>
              <div class="editorChart_data form-layout">
                <%= f.select :data5, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
              </div>
            </div>
          </div>
          <%= f.submit '更新する', class: 'btn btn-default btn-submit' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "chart.js" %>

app/views/articles/content.html.erb
<div class="article-edit-body">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render 'edit' %>
      </div>
      <div class="col-md-8">
        <h2 class="edit-title">投稿内容を編集する </h2>
        <div class="edit-main">
          <%= form_for @article do |f| %>
            <div class="form-group">
              <%= f.text_area :content, rows: 6, cols: 60, placeholder: '投稿内容', class: 'form-control' %>
            </div>
            <%= f.submit '更新する', class: 'btn btn-default btn-submit' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= provide(:title, '新規投稿') %>
<div class="articleEditor">
    <%= form_for @article do |f| %>
        <%= render "shared/message", object: @article %>
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="articleEditor_form">
                        <div class="editorTitle">
                            <div class="form-group">
                                <%= f.label :title, 'タイトル', class: 'form-label' %>
                                <div class="form-layout">
                                    <h6><span class="badge badge-danger">必須</span></h6>
                                    <%= f.text_field :title, placeholder: 'タイトルを入力してください', class: 'form-control' %>
                                </div>
                            </div>
                        </div>
                        <div class="editorContent editorFrom_border">
                            <div class="form-group">
                                <%= f.label :content, '投稿内容', class: 'form-label' %>
                                <div class="form-layout">
                                    <h6><span class="badge badge-danger">必須</span></h6>
                                    <%= f.text_area :content, rows: 6, cols: 60, placeholder: '内容を入力してください', class: 'form-control' %>
                                </div>
                            </div>
                        </div>
                        <div class="editorPicture editorFrom_border">
                            <label class="form-label">写真を追加する</label>
                            <div id="preview-thumbnails"></div>
                            <%= f.fields_for :pictures do |picture| %>
                                <%= picture.file_field :image, class: 'hidden' %>
                            <% end %>
                        </div>
                        <div class="editorChart editorFrom_border">
                            <label class="form-label">グラフを作成する</label>
                            <canvas id="myChart"></canvas>
                            <div class="editorChart_form">
                                <div class="editorChart_box">
                                    <div class="editorChart_label form-layout">
                                        <h6><span class="badge badge-danger">必須</span></h6>
                                        <%= f.text_field :label1, placeholder: 'ラベル１', class: 'form-control mr-3' %>
                                    </div>
                                    <div class="editorChart_data form-layout">
                                        <h6><span class="badge badge-danger">必須</span></h6>
                                        <%= f.select :data1, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
                                    </div>
                                </div>
                                <div class="editorChart_box">
                                    <div class="editorChart_label form-layout">
                                        <h6><span class="badge badge-danger">必須</span></h6>
                                        <%= f.text_field :label2, placeholder: 'ラベル2', class: 'form-control mr-3' %>
                                    </div>
                                    <div class="editorChart_data form-layout">
                                        <h6><span class="badge badge-danger">必須</span></h6>
                                        <%= f.select :data2, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
                                    </div>
                                </div>
                                <div class="editorChart_box">
                                    <div class="editorChart_label form-layout">
                                        <h6><span class="badge badge-danger">必須</span></h6>
                                        <%= f.text_field :label3, placeholder: 'ラベル3', class: 'form-control mr-3' %>
                                    </div>
                                    <div class="editorChart_data form-layout">
                                        <h6><span class="badge badge-danger">必須</span></h6>
                                        <%= f.select :data3, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
                                    </div>
                                </div>
                                <div class="editorChart_box">
                                    <div class="editorChart_label form-layout">
                                        <%= f.text_field :label4, placeholder: 'ラベル4', class: 'form-control mr-3' %>
                                    </div>
                                    <div class="editorChart_data form-layout">
                                        <%= f.select :data4, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
                                    </div>
                                </div>
                                <div class="editorChart_box">
                                    <div class="editorChart_label form-layout">
                                        <%= f.text_field :label5, placeholder: 'ラベル5', class: 'form-control mr-3' %>
                                    </div>
                                    <div class="editorChart_data form-layout">
                                        <%= f.select :data5, [1, 2, 3, 4, 5], { include_blank: '選択して下さい' }, class: 'custom-select' %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="editorSubmit">
                            <%= f.submit '投稿する', class: 'btn btn-default btn-submit' %>
                        </div>
                    </div>
                </div>  
            <div class="col-md-2"></div>
            </div>
        </div>
    <% end %>
</div>
<%= javascript_include_tag "sample_chart.js", "new_article.js" %>

app/views/articles/pictures.html.erb
<div class="article-edit-body">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render 'edit' %>
      </div>
      <div class="col-md-8">
        <div class="edit-form-container">
          <h2 class="edit-title">写真</h2>
          <div class="pictures-body">
            <div class="picture-upload">
              <%= form_with model: @picture do |f| %>
                <div id="selectPhoto" class="select-photo">写真を追加する</div>
                <%= f.file_field :image, class: 'hidden', id: 'add-picture' %>
                <%= f.hidden_field :article_id, value: @article.id %>
                <%= f.submit '更新する', class: 'btn btn-default btn-submit btn-picture' %>
              <% end %>
            </div>
            <div class="pictures-container">
              <ul id="picturesList">
                <%= render 'pictures/pictures_list' %>
            </ul>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "pictures.js" %>

app/views/articles/show.html.erb
<%= provide(:title, @article.title) %>
<div class="articleWrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <div class="article-main">
                    <div class="article-header">
                        <h1 class="header-title"> <%= @article.title %> </h1>
                        <div class="article-updated">
                                <%= @article.updated_at.strftime('%Y年%m月%d日') %>
                        </div>
                    </div>
                    <% if user_signed_in? %>
                        <div class="articleActions">
                            <% if likes?(@article.id) %>
                                <%= render 'likes/liked' %>
                            <% else %>
                                <%= render 'likes/likable' %>
                            <% end %>
                            <% if favorite?(@article) %>
                                <%= render 'favorites/unfavorite' %>
                            <% else %>
                                <%= render 'favorites/favorites' %>
                            <% end %>        
                        </div>
                    <% end %>
                    <section class="articleContent">
                        <% if @pictures.size > 0 %>
                            <div class="articlePicture">
                                <div class="article-thumbnails">
                                    <ul id="thumbnails">
                                        <% @pictures.each do |picture| %>
                                            <li class="thumbnail-list"> <%= image_tag picture.image_url, class: 'thumbnail' %> </li>
                                        <% end %>
                                    </ul>
                                </div>
                                <main> 
                                    <%= image_tag @pictures[0].image_url, class: 'main-picture' %>
                                </main>
                            </div>
                        <% end %>
                        <div class="articleContent_story">
                            <%= simple_format(@article.content) %>
                        </div>
                        <div class="articleContent_chart">
                            <canvas id="myRadarChart"></canvas>
                        </div>
                    </section>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="article-sideMenu">
                    <div class="sideMenu_header">
                        <%= image_tag @article.user.avatar.to_s, class: 'author-image' %>
                        <div class="sideMenu_header_label">
                            <%= link_to @article.user.name, @article.user %>
                        </div>
                    </div>
                    <div class="author-introduce">
                        <%= @article.user.introduce %>
                    </div>
                    <% if user_signed_in? %>
                        <% if correct_user? %>
                            <div class="sideMenu_meta">
                                <div class="article-view-count">
                                    <%= @article.view_count %><span style="margin-left: 3px;">views</span>
                                </div>
                                <div class="article-settings">
                                    <%= link_to '編集する', title_article_path(@article) %>
                                    <%= link_to '削除する', article_path(@article), method: :delete, data: { confirm: '本当に削除しますか?' } %>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="commentsWrapper">
        <div class="comment-main">
            <%= render 'comments/comment_list' %>
            <% if user_signed_in? %>
                <%= render 'comments/comment_form', object: @new_comment %>
            <% else %>
                <div class="anonymousForm">
                    <div class="anonymousForm_lead">
                        あなたもコメントしてみませんか
                    </div>
                    <%= link_to '登録', signup_path, class: 'btn btn-default' %>
                    <div class="anonymousForm_sub">
                        すでにアカウントをお持ちの方は<%= link_to 'ログイン', login_path %>
                    </div>

                </div>
            <% end %>
        </div>
    </div>
</div>
<%= javascript_include_tag "chart.js", "articles.js" %>

app/views/articles/title.html.erb
<div class="article-edit-body">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render 'edit' %>
      </div>
      <div class="col-md-8">
        <h2 class="edit-title">タイトルを編集する </h2>
        <div class="edit-main">
          <%= form_for @article do |f| %>
            <div class="form-group">
              <%= f.text_field :title, placeholder: 'タイトル', class: 'form-control' %>
            </div>
            <%= f.submit '更新する', class: 'btn btn-default btn-submit' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>