config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
            skip: [:sessions, :passwords, :registrations]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    get "setting/profile", to: "users/registrations#edit"
    patch "setting/profile", to: "users/registrations#update"
    delete "delete", to: "users/registrations#destroy"
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    delete "logout", to: "users/sessions#destroy"
    get "forgot_password", to: "users/passwords#new"
    post "forgot_password", to: "users/passwords#create"
    get "password_reset", to: "users/passwords#edit"
    put "password_reset", to: "users/passwords#update"
  end

  get "search", to: "pages#search"

  get "setting/password", to: "users#edit"
  patch "setting/password", to: "users#update_password"
  get "about", to: "pages#about"

  resources :users, only: :show do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: [:index]

  # resources :rooms, only: [:index, :show, :create, :update, :destroy]

  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :title, :content, :pictures, :chart
    end
  end

  resources :pictures, only: [:create, :destroy]

  resources :comments, only: [:create, :edit, :update, :destroy] do
    member do
      get :cancel
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "pages#home"

  mount ActionCable.server => "/cable"
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :user

  def self.count_unread
    Notification.where(user_id: Current.user.id, already: false).count
  end

  def article
    Article.find_by(id: self.article_id)
  end

  delegate :title, to: :article, prefix: true

  def user_name(user_id)
    User.find_by(id: user_id).name
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  def index
    current_user.update(unread: 0)
    @notifications = current_user.notifications.order(created_at: :desc).page(params[:page]).per(10)
    @notification_count = current_user.notifications.count
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
  def already_read?
    current_user.notifications.all? { |notification| notification.already? }
  end
end

app/views/notifications/index.html.erb
<div class="container notifications">
  <div class='row'>
    <div class='col-md-2'></div>
    <div class="col-md-8">
      <% if @notification_count > 0 %>
        <% @notifications.each do |notification| %>
          <% if notification.article_id.nil? %>
            <%= link_to user_path(User.find(notification.follower_id)), class: "notification-link" do %>
              <div class="notification-wrapper">
                  <div class="notification-content"><%= notification.content %></div>
                  <time class="notification-datetime"><%= notification.created_at.strftime("%Y/%m/%d") %></time>
              </div>
            <% end %>
          <% else %>
            <%= link_to article_path(Article.find(notification.article_id)), class: "notification-link"  do %>
              <div class="notification-wrapper">
                  <div class="notification-content"><%= notification.content %></div>
                  <time class="notification-datetime"><%= notification.created_at.strftime("%Y/%m/%d") %></time>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <div class="pagenation">
          <%= paginate @notifications %>
        </div>
      <% else %>
        <div class="no-content">通知はありません。</div>
      <% end %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>