config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
            skip: [:sessions, :passwords, :registrations]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    get "setting/profile", to: "users/registrations#edit"
    patch "setting/profile", to: "users/registrations#update"
    delete "delete", to: "users/registrations#destroy"
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    delete "logout", to: "users/sessions#destroy"
    get "forgot_password", to: "users/passwords#new"
    post "forgot_password", to: "users/passwords#create"
    get "password_reset", to: "users/passwords#edit"
    put "password_reset", to: "users/passwords#update"
  end

  get "search", to: "pages#search"

  get "setting/password", to: "users#edit"
  patch "setting/password", to: "users#update_password"
  get "about", to: "pages#about"

  resources :users, only: :show do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: [:index]

  # resources :rooms, only: [:index, :show, :create, :update, :destroy]

  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :title, :content, :pictures, :chart
    end
  end

  resources :pictures, only: [:create, :destroy]

  resources :comments, only: [:create, :edit, :update, :destroy] do
    member do
      get :cancel
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "pages#home"

  mount ActionCable.server => "/cable"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.name = name.downcase }

  after_destroy_commit :delete_notifications

  extend FriendlyId
  friendly_id :name, use: :slugged

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :active_relationships,
    class_name: "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships,
    class_name: "Relationship",
    foreign_key: "followed_id",
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name,
    presence: true,
    length: { in: 3..20 },
    format: { with: /\A[\w@-]*[A-Za-z][\w@-]*\z/ }, # 半角英数字のみ ただし数字のみは不可
    uniqueness: { case_sensitive: false },
    ban_reserved: true

  validates :introduce,
    length: { maximum: 200 }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Article.includes(:user).where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id).order(created_at: :desc)
  end

  def self.find_for_oauth(auth)
    user = User.find_by(uid: auth.uid, provider: auth.provider)

    unless user
      user = User.create(
        uid: auth.uid,
        provider: auth.provider,
        email: User.get_email(auth),
        password: Devise.friendly_token[0, 20],
        name: auth.info.nickname,
        remote_avatar_url: auth.info.image
      )
    end

    return user
  end

  def self.get_email(auth)
    auth.info.email || "#{auth.uid}-#{auth.provider}@example.com"
  end

  private

    def delete_notifications
      Notification.where(follower_id: self.id).destroy_all
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private
    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = "ログインしました。"
        sign_in_and_redirect @user, event: :authentication
      else
        redirect_to signup_path, alert: "ユーザー認証に失敗しました。"
      end
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      redirect_to root_url, notice: "メールを送信しました"
    else
      render "new"
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      redirect_to login_url, notice: "新しいパスワードでログインしてください。"
    else
      set_minimum_password_length
      render "edit"
    end
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduce, :avatar, :remove_avatar])
  end

  def after_update_path_for(resource)
      setting_profile_path(current_user)
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:edit, :update_password]

    def show
        @user = User.friendly.find(params[:id])
        @articles = @user.articles.order(created_at: :desc)
        @liked_articles = Article.includes(:user).joins(:likes).where(likes: { user: @user })
        @feed = @user.feed
    end

    def edit
        @user = current_user
    end

    def following
        @user = User.find_by(name: params[:id])
        @following_user = @user.following
    end

    def followers
        @user = User.find_by(name: params[:id])
        @followers_user = @user.followers
    end

    def update_password
        @user = current_user
        if @user.update(user_params)
            bypass_sign_in(@user)
            redirect_to root_url, notice: "パスワードが変更されました。"
        else
            flash.now[:alert] = "入力に誤りがあります。"
            render "edit"
        end
    end

    private

        def user_params
            params.require(:user).permit(:password, :password_confirmation)
        end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<div class="container setting-profile">
    <div class="row">
        <div class="col-md-3">
            <div class="settings-profile-menu">
                <%= link_to 'プロフィール', setting_profile_path %>
                <%= link_to 'パスワード', setting_password_path %>
            </div>
        </div>
        <div class="col-md-9">
            <div class="form settings-profile-main">
                <%= form_for(@user, url: { action: 'update_password'}) do |f| %>
                    <div class="form-group">
                        <%= f.label :password, class: 'form-label' %>
                        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
                    </div>

                    <div class="form-group">
                        <%= f.label :password_confirmation, '確認用パスワード', class: 'form-label' %>
                        <%= f.password_field :password_confirmation, class: 'form-control' %>
                    </div>
                    <%= f.submit '変更する', class: 'btn btn-default' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/followers.html.erb
<div class="main">
    <div class="userPage_header">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="userPage_profile">
                        <div class="userPage_avatar">
                            <%= link_to @user do %>
                                <%= image_tag @user.avatar.to_s, size: '80x80' %>
                            <% end %>
                        </div>
                        <div class="userPage_body">
                            <h2 class="userPage_heading"> <%= @user.name %> </h2>
                            <p>
                                <span class="userPage_articleCount"><%= @user.articles.count %></span>
                                <span class="userPage_posts">Posting</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4"></div>
            </div>
        </div>
    </div>
    <div class="userPage_ribbon">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <span class="userPage_ribbonTitle"> <%= link_to @user.name, @user %> / フォロワー </span>
                </div>
            </div>
        </div>
    </div>
    <div class="userPage_main">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="tabList">
                        <% @followers_user.each do |user| %>
                            <div class="tabList_Item">
                                <div class="tabList_avatar"><%= image_tag user.avatar.to_s, size: '48x48' %></div>
                                <div class="tabList_info">
                                    <%= link_to user.name, user %>
                                    <p><%= user.introduce %></p>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'shared/footer' %>

app/views/users/following.html.erb
<div class="main">
    <div class="userPage_header">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="userPage_profile">
                        <div class="userPage_avatar">
                            <%= link_to @user do %>
                                <%= image_tag @user.avatar.to_s, size: '80x80' %>
                            <% end %>
                        </div>
                        <div class="userPage_body">
                            <h2 class="userPage_heading"> <%= @user.name %> </h2>
                            <p>
                                <span class="userPage_articleCount"><%= @user.articles.count %></span>
                                <span class="userPage_posts">Posting</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4"></div>
            </div>
        </div>
    </div>
    <div class="userPage_ribbon">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <span class="userPage_ribbonTitle"> <%= link_to @user.name, @user %> / フォロー中のユーザー </span>
                </div>
            </div>
        </div>
    </div>
    <div class="userPage_main">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="tabList">
                        <% @following_user.each do |user| %>
                            <div class="tabList_Item">
                                <div class="tabList_avatar"><%= image_tag user.avatar.to_s, size: '48x48' %></div>
                                <div class="tabList_info">
                                    <%= link_to user.name, user %>
                                    <p><%= user.introduce %></p>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'shared/footer' %>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div id="main">
    <div class="container userPage">
        <div class="row">
            <div class="col-md-3">
                <div class="profile-avatar">
                    <%= image_tag @user.avatar.to_s %>
                </div>
                <div class="profile-username">
                    <h3> <%= @user.name %> </h3>
                </div>
                <% if user_signed_in? %>
                    <% unless current_user?(@user) %>
                        <% if current_user.following?(@user) %>
                            <%= render 'relationships/unfollow' %>
                        <% else %>
                            <%= render 'relationships/follow' %>
                        <% end %>
                    <% end %>
                <% end %>
                <div class="profile-info">
                    <% unless @user.introduce.nil? %>
                        <div class="profile-introduce">
                            <%= @user.introduce %>
                        </div>
                    <% end %>
                    <% if current_user?(@user) %>
                        <%= link_to setting_profile_path, class: 'edit-profile' do %>
                            <i class="fas fa-cog"></i> プロフィールを編集する
                        <% end %>
                    <% end %>
                </div>
                <div class="profileUser_following">
                    <div class="profileUser_following-header">
                        <div class="profileUser_following-title"> <i class="fas fa-users"></i> フォロー中のユーザー </div>
                        <%= link_to @user.following.count, following_user_path, class: 'profileUser_following-count' %>
                    </div>
                    <div class="profileUser_following-body">
                        <ul>
                            <% @user.following.each do |user| %>
                                <li>
                                    <%= link_to user do %> 
                                        <%= image_tag user.avatar.to_s %>
                                    <% end %>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <div class="profileUser_following">
                    <div class="profileUser_following-header">
                        <div class="profileUser_following-title"> <i class="fas fa-user-check"></i> フォロワーリスト </div>
                        <%= link_to @user.followers.count, followers_user_path, class: 'profileUser_following-count' %>
                    </div>
                    <div class="profileUser_following-body">
                        <ul>
                            <% @user.followers.each do |user| %>
                                <li>
                                    <%= link_to user do %> 
                                        <%= image_tag user.avatar.to_s %>
                                    <% end %>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item active">
                        <a href="#timeline" class="nav-link posted-tab" id="timeline-tab" data-toggle="tab" role="tab" aria-controls="timeline" aria-selected="true">タイムライン</a>
                    </li>
                    <li class="nav-item">
                        <a href="#posted-articles" id="posted-articles-tab" data-toggle="tab" class="nav-link posted-tab" role="tab" aria-controls="posted-articles" aria-selected="true">投稿した記事</a>
                    </li>
                    <li class="nav-item">
                        <a href="#liked-articles" id="liked-articles-tab" data-toggle="tab" class="nav-link posted-tab" role="tab" aria-controls="liked-articles" aria-selected="false">いいねした記事</a>
                    </li>
                </ul>
                <div class="tab-content mt-3" id="myTabContent">
                    <div class="tab-pane fade show active" id="timeline" role="tabpanel" aria-labelledby="timeline-tab">
                        <%= render 'articles/articles', object: @feed %>
                    </div>
                    <div class="tab-pane fade show" id="posted-articles" role="tabpanel" aria-labelledby="posted-articles-tab">
                        <%= render 'articles/articles', object: @articles %>
                    </div>
                    <div class="tab-pane fade show" id="liked-articles" role="tabpanel" aria-labelledby="liked-articles-tab">
                        <%= render 'articles/articles', object: @liked_articles %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'shared/footer' %>