config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
            skip: [:sessions, :passwords, :registrations]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    get "setting/profile", to: "users/registrations#edit"
    patch "setting/profile", to: "users/registrations#update"
    delete "delete", to: "users/registrations#destroy"
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    delete "logout", to: "users/sessions#destroy"
    get "forgot_password", to: "users/passwords#new"
    post "forgot_password", to: "users/passwords#create"
    get "password_reset", to: "users/passwords#edit"
    put "password_reset", to: "users/passwords#update"
  end

  get "search", to: "pages#search"

  get "setting/password", to: "users#edit"
  patch "setting/password", to: "users#update_password"
  get "about", to: "pages#about"

  resources :users, only: :show do
    resources :favorites, only: [:index, :create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: [:index]

  # resources :rooms, only: [:index, :show, :create, :update, :destroy]

  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :title, :content, :pictures, :chart
    end
  end

  resources :pictures, only: [:create, :destroy]

  resources :comments, only: [:create, :edit, :update, :destroy] do
    member do
      get :cancel
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "pages#home"

  mount ActionCable.server => "/cable"
end

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="footer-logo">LoveKitchen</div>
            </div>
            <div class="col-md-8 text-right">
                <ul>
                    <li class="footer-item"> <%= link_to 'TOP', root_path %> </li>
                    <li class="footer-item"> <%= link_to 'LoveKitchenとは', about_path %> </li>
                    <li class="footer-item"> <%= link_to '投稿', new_article_path %> </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/shared/_message.html.erb
<% unless object.errors.empty? %>
  <script type="text/javascript">
    <% object.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-fixed-top navbar-expand-md navbar-dark bg-dark navbar-custom">
    <div class="container">
        <%= link_to 'LoveKitchen', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-content">
            <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                    <li class="nav-item mr-sm-2 nav-search">
                        <%= render 'shared/search_form'%>
                    </li>
                    <li class="nav-item"> 
                        <%= link_to user_favorites_path(current_user), data: { tip: 'お気に入り' }, class: 'tips nav-link icon-link' do %>
                            <i class="fas fa-heart"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to new_article_path, class: 'nav-link' do %>
                            <i class="fas fa-edit"></i> 投稿する
                        <% end %>
                    </li>
                    <li class="nav-item notification-bar">
                        <%= link_to notifications_path, class: 'nav-link' do %>
                            <% if current_user.unread > 0 %>
                                <div class='unread'><span class="notification-count"><%= current_user.unread %></span></div>
                            <% end %>
                            <i class="fas fa-bell"></i>
                        <% end %>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= image_tag current_user.avatar.to_s, size: '35x35'%>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to current_user, class: 'nav-link' do %>
                                <i class="fas fa-user-alt"></i> プロフィール
                            <% end %>
                            <div class="dropdown-divider"></div>
                            <%= link_to logout_path, method: :delete, class: 'nav-link' do %>
                                <i class="fas fa-sign-out-alt"></i> ログアウト
                            <% end %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to about_path, class: 'nav-link' do %>
                            <i class="fas fa-utensils"></i> LoveKitchenとは
                        <% end %>
                    </li>
                    <li class="nav-item"> 
                        <%= link_to signup_path, class: 'nav-link' do %>
                            <i class="fas fa-rocket"></i> 無料会員登録
                        <% end %>
                    </li>
                    <li class="nav-item"> 
                        <%= link_to login_path, class: 'nav-link' do %>
                            <i class="fas fa-lock"></i> ログイン
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, url: search_path, class: 'form-inline', id: "search-article-form" do |f| %>
    <%= f.search_field :title_or_content_cont, placeholder: 'キーワードを入力', class: 'search-field search-input' %>
    <%= button_tag type: 'submit', class: 'search-box' do %>
        <i class="fas fa-search"></i>
    <% end %>
<% end %>
<%= javascript_include_tag "navbar.js" %>